name: Build, Test

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: macos-12

   steps:
   - uses: actions/checkout@v3
   
   - name: Build and Test
     run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
